name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version
        id: version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Create ZIP
        run: |
          cd custom_components/smart_toilet
          zip -r ../../smart_toilet.zip . -x "*.pyc" "__pycache__/*" "*.pyo"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: smart_toilet.zip
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
